export interface EmojiItem {
  name: string
  index: number
  path: string
  asset: any
}

export const EmojiList: EmojiItem[] = [
  {
    name: '[/微笑]',
    index: 0,
    path: 'weixiao.png',
    asset: require('./weixiao.png'),
  },
  { name: '[/色]', index: 1, path: 'aimu.png', asset: require('./aimu.png') },
  {
    name: '[/发呆]',
    index: 2,
    path: 'liangdai.png',
    asset: require('./liangdai.png'),
  },
  {
    name: '[/酷拽]',
    index: 3,
    path: 'kuye.png',
    asset: require('./kuye.png'),
  },
  {
    name: '[/抠鼻]',
    index: 4,
    path: 'koubi.png',
    asset: require('./koubi.png'),
  },
  {
    name: '[/流泪]',
    index: 5,
    path: 'liulei.png',
    asset: require('./liulei.png'),
  },
  {
    name: '[/捂脸]',
    index: 6,
    path: 'wulian.png',
    asset: require('./wulian.png'),
  },
  {
    name: '[/发怒]',
    index: 7,
    path: 'fanu.png',
    asset: require('./fanu.png'),
  },
  {
    name: '[/呲牙]',
    index: 8,
    path: 'ziya.png',
    asset: require('./ziya.png'),
  },
  {
    name: '[/一起加油]',
    index: 9,
    path: 'yiqijiayou.png',
    asset: require('./yiqijiayou.png'),
  },
  {
    name: '[/害羞]',
    index: 10,
    path: 'haixiu.png',
    asset: require('./haixiu.png'),
  },
  {
    name: '[/调皮]',
    index: 11,
    path: 'keai.png',
    asset: require('./keai.png'),
  },
  { name: '[/晕]', index: 12, path: 'yun.png', asset: require('./yun.png') },
  {
    name: '[/衰]',
    index: 13,
    path: 'shuai.png',
    asset: require('./shuai.png'),
  },
  {
    name: '[/闭嘴]',
    index: 14,
    path: 'bizui.png',
    asset: require('./bizui.png'),
  },
  {
    name: '[/机智]',
    index: 15,
    path: 'jizhi.png',
    asset: require('./jizhi.png'),
  },
  { name: '[/赞]', index: 16, path: 'zan.png', asset: require('./zan.png') },
  {
    name: '[/鼓掌]',
    index: 17,
    path: 'guzhang.png',
    asset: require('./guzhang.png'),
  },
  {
    name: '[/感谢]',
    index: 18,
    path: 'qidao.png',
    asset: require('./qidao.png'),
  },
  {
    name: '[/抱抱你]',
    index: 19,
    path: 'baobaoni.png',
    asset: require('./baobaoni.png'),
  },
  {
    name: '[/来看我]',
    index: 20,
    path: 'laikanwo.png',
    asset: require('./laikanwo.png'),
  },
  {
    name: '[/灵机一动]',
    index: 21,
    path: 'lingguangyishan.png',
    asset: require('./lingguangyishan.png'),
  },
  { name: '[/耶]', index: 22, path: 'ye.png', asset: require('./ye.png') },
  {
    name: '[/打脸]',
    index: 23,
    path: 'dalian.png',
    asset: require('./dalian.png'),
  },
  {
    name: '[/大笑]',
    index: 24,
    path: 'daxiao.png',
    asset: require('./daxiao.png'),
  },
  {
    name: '[/哈欠]',
    index: 25,
    path: 'haqian.png',
    asset: require('./haqian.png'),
  },
  {
    name: '[/震惊]',
    index: 26,
    path: 'zhenliang.png',
    asset: require('./zhenliang.png'),
  },
  {
    name: '[/送心]',
    index: 27,
    path: 'songxin.png',
    asset: require('./songxin.png'),
  },
  { name: '[/困]', index: 28, path: 'kun.png', asset: require('./kun.png') },
  {
    name: '[/疑问]',
    index: 29,
    path: 'what.png',
    asset: require('./what.png'),
  },
  {
    name: '[/泣不成声]',
    index: 30,
    path: 'qibuchengsheng.png',
    asset: require('./qibuchengsheng.png'),
  },
  {
    name: '[/小鼓掌]',
    index: 31,
    path: 'xiaoguzhang.png',
    asset: require('./xiaoguzhang.png'),
  },
  {
    name: '[/大金牙]',
    index: 32,
    path: 'dajinya.png',
    asset: require('./dajinya.png'),
  },
  {
    name: '[/偷笑]',
    index: 33,
    path: 'touxiao.png',
    asset: require('./touxiao.png'),
  },
  {
    name: '[/石化]',
    index: 34,
    path: 'shihua.png',
    asset: require('./shihua.png'),
  },
  {
    name: '[/思考]',
    index: 35,
    path: 'sikao.png',
    asset: require('./sikao.png'),
  },
  {
    name: '[/吐血]',
    index: 36,
    path: 'tuxie.png',
    asset: require('./tuxie.png'),
  },
  {
    name: '[/可怜]',
    index: 37,
    path: 'kelian.png',
    asset: require('./kelian.png'),
  },
  { name: '[/嘘]', index: 38, path: 'xu.png', asset: require('./xu.png') },
  {
    name: '[/撇嘴]',
    index: 39,
    path: 'piezui.png',
    asset: require('./piezui.png'),
  },
  {
    name: '[/笑哭]',
    index: 40,
    path: 'xiaoku.png',
    asset: require('./xiaoku.png'),
  },
  {
    name: '[/奸笑]',
    index: 41,
    path: 'jianxiao.png',
    asset: require('./jianxiao.png'),
  },
  {
    name: '[/得意]',
    index: 42,
    path: 'deyi.png',
    asset: require('./deyi.png'),
  },
  {
    name: '[/憨笑]',
    index: 43,
    path: 'hanxiao.png',
    asset: require('./hanxiao.png'),
  },
  {
    name: '[/坏笑]',
    index: 44,
    path: 'huaixiao.png',
    asset: require('./huaixiao.png'),
  },
  {
    name: '[/抓狂]',
    index: 45,
    path: 'zhuakuang.png',
    asset: require('./zhuakuang.png'),
  },
  {
    name: '[/泪奔]',
    index: 46,
    path: 'leiben.png',
    asset: require('./leiben.png'),
  },
  { name: '[/钱]', index: 47, path: 'qian.png', asset: require('./qian.png') },
  {
    name: '[/恐惧]',
    index: 48,
    path: 'kongju.png',
    asset: require('./kongju.png'),
  },
  {
    name: '[/愉快]',
    index: 49,
    path: 'xiao.png',
    asset: require('./xiao.png'),
  },
  {
    name: '[/快哭了]',
    index: 50,
    path: 'kuaikule.png',
    asset: require('./kuaikule.png'),
  },
  {
    name: '[/翻白眼]',
    index: 51,
    path: 'fanbaiyan.png',
    asset: require('./fanbaiyan.png'),
  },
  {
    name: '[/互粉]',
    index: 52,
    path: 'hufen.png',
    asset: require('./hufen.png'),
  },
  {
    name: '[/我想静静]',
    index: 53,
    path: 'woxiangjingjing.png',
    asset: require('./woxiangjingjing.png'),
  },
  {
    name: '[/委屈]',
    index: 54,
    path: 'weiqu.png',
    asset: require('./weiqu.png'),
  },
  {
    name: '[/舔屏]',
    index: 55,
    path: 'tianping.png',
    asset: require('./tianping.png'),
  },
  {
    name: '[/鄙视]',
    index: 56,
    path: 'bishi.png',
    asset: require('./bishi.png'),
  },
  {
    name: '[/飞吻]',
    index: 57,
    path: 'feiwen.png',
    asset: require('./feiwen.png'),
  },
  {
    name: '[/再见]',
    index: 58,
    path: 'zaijian.png',
    asset: require('./zaijian.png'),
  },
  {
    name: '[/紫薇别走]',
    index: 59,
    path: 'ziweibiezou.png',
    asset: require('./ziweibiezou.png'),
  },
  {
    name: '[/听歌]',
    index: 60,
    path: 'tingge.png',
    asset: require('./tingge.png'),
  },
  {
    name: '[/求抱抱]',
    index: 61,
    path: 'qiubaobao.png',
    asset: require('./qiubaobao.png'),
  },
  {
    name: '[/绝望的凝视]',
    index: 62,
    path: 'zhoudongyudeningshi.png',
    asset: require('./zhoudongyudeningshi.png'),
  },
  {
    name: '[/不失礼貌的微笑]',
    index: 63,
    path: 'masichundeweixiao.png',
    asset: require('./masichundeweixiao.png'),
  },
  {
    name: '[/不看]',
    index: 64,
    path: 'bukan.png',
    asset: require('./bukan.png'),
  },
  {
    name: '[/裂开]',
    index: 65,
    path: 'liekai.png',
    asset: require('./liekai.png'),
  },
  {
    name: '[/干饭人]',
    index: 66,
    path: 'ganfanren.png',
    asset: require('./ganfanren.png'),
  },
  {
    name: '[/吐舌]',
    index: 67,
    path: 'tushe.png',
    asset: require('./tushe.png'),
  },
  {
    name: '[/呆无辜]',
    index: 68,
    path: 'daiwugu.png',
    asset: require('./daiwugu.png'),
  },
  { name: '[/看]', index: 69, path: 'kan.png', asset: require('./kan.png') },
  {
    name: '[/白眼]',
    index: 70,
    path: 'baiyan.png',
    asset: require('./baiyan.png'),
  },
  {
    name: '[/熊吉]',
    index: 71,
    path: 'xiongji.png',
    asset: require('./xiongji.png'),
  },
  {
    name: '[/猪头]',
    index: 72,
    path: 'zhutou.png',
    asset: require('./zhutou.png'),
  },
  {
    name: '[/冷漠]',
    index: 73,
    path: 'lengmo.png',
    asset: require('./lengmo.png'),
  },
  {
    name: '[/微笑袋鼠]',
    index: 74,
    path: 'weixiaodaishu.png',
    asset: require('./weixiaodaishu.png'),
  },
  {
    name: '[/凝视]',
    index: 75,
    path: 'ningshi.png',
    asset: require('./ningshi.png'),
  },
  {
    name: '[/暗中观察]',
    index: 76,
    path: 'anzhongguancha.png',
    asset: require('./anzhongguancha.png'),
  },
  {
    name: '[/二哈]',
    index: 77,
    path: 'erha.png',
    asset: require('./erha.png'),
  },
  {
    name: '[/菜狗]',
    index: 78,
    path: 'caigou.png',
    asset: require('./caigou.png'),
  },
  {
    name: '[/黑脸]',
    index: 79,
    path: 'heilian.png',
    asset: require('./heilian.png'),
  },
  {
    name: '[/吃瓜群众]',
    index: 80,
    path: 'chiguaqunzhong.png',
    asset: require('./chiguaqunzhong.png'),
  },
  {
    name: '[/绿帽子]',
    index: 81,
    path: 'lvmaozi.png',
    asset: require('./lvmaozi.png'),
  },
  {
    name: '[/摸头]',
    index: 82,
    path: 'motou.png',
    asset: require('./motou.png'),
  },
  {
    name: '[/皱眉]',
    index: 83,
    path: 'zhoumei.png',
    asset: require('./zhoumei.png'),
  },
  {
    name: '[/擦汗]',
    index: 84,
    path: 'cahan.png',
    asset: require('./cahan.png'),
  },
  {
    name: '[/红脸]',
    index: 85,
    path: 'honglian.png',
    asset: require('./honglian.png'),
  },
  {
    name: '[/尬笑]',
    index: 86,
    path: 'gaxiao.png',
    asset: require('./gaxiao.png'),
  },
  {
    name: '[/做鬼脸]',
    index: 87,
    path: 'zuoguilian.png',
    asset: require('./zuoguilian.png'),
  },
  {
    name: '[/强]',
    index: 88,
    path: 'qiang.png',
    asset: require('./qiang.png'),
  },
  {
    name: '[/如花]',
    index: 89,
    path: 'ruhua.png',
    asset: require('./ruhua.png'),
  },
  { name: '[/吐]', index: 90, path: 'tu.png', asset: require('./tu.png') },
  {
    name: '[/惊喜]',
    index: 91,
    path: 'liangxi.png',
    asset: require('./liangxi.png'),
  },
  {
    name: '[/敲打]',
    index: 92,
    path: 'qiaoda.png',
    asset: require('./qiaoda.png'),
  },
  {
    name: '[/奋斗]',
    index: 93,
    path: 'fendou.png',
    asset: require('./fendou.png'),
  },
  {
    name: '[/吐彩虹]',
    index: 94,
    path: 'tucaihong.png',
    asset: require('./tucaihong.png'),
  },
  {
    name: '[/大哭]',
    index: 95,
    path: 'daku.png',
    asset: require('./daku.png'),
  },
  {
    name: '[/嘿哈]',
    index: 96,
    path: 'heiha.png',
    asset: require('./heiha.png'),
  },
  {
    name: '[/加好友]',
    index: 97,
    path: 'jiahaoyou.png',
    asset: require('./jiahaoyou.png'),
  },
  {
    name: '[/惊恐]',
    index: 98,
    path: 'jingkong.png',
    asset: require('./jingkong.png'),
  },
  {
    name: '[/惊讶]',
    index: 99,
    path: 'jingya.png',
    asset: require('./jingya.png'),
  },
  {
    name: '[/囧]',
    index: 100,
    path: 'jiong.png',
    asset: require('./jiong.png'),
  },
  {
    name: '[/难过]',
    index: 101,
    path: 'nanguo.png',
    asset: require('./nanguo.png'),
  },
  {
    name: '[/斜眼]',
    index: 102,
    path: 'xieyan.png',
    asset: require('./xieyan.png'),
  },
  {
    name: '[/阴险]',
    index: 103,
    path: 'yinxian.png',
    asset: require('./yinxian.png'),
  },
  {
    name: '[/悠闲]',
    index: 104,
    path: 'youxian.png',
    asset: require('./youxian.png'),
  },
  {
    name: '[/咒骂]',
    index: 105,
    path: 'zhouma.png',
    asset: require('./zhouma.png'),
  },
  {
    name: '[/比心]',
    index: 106,
    path: 'bixin.png',
    asset: require('./bixin.png'),
  },
  {
    name: '[/强壮]',
    index: 107,
    path: 'jiayou.png',
    asset: require('./jiayou.png'),
  },
  {
    name: '[/碰拳]',
    index: 108,
    path: 'pengquan.png',
    asset: require('./pengquan.png'),
  },
  { name: '[/OK]', index: 109, path: 'ok.png', asset: require('./ok.png') },
  {
    name: '[/击掌]',
    index: 110,
    path: 'jizhang.png',
    asset: require('./jizhang.png'),
  },
  {
    name: '[/左上]',
    index: 111,
    path: 'zuoshang.png',
    asset: require('./zuoshang.png'),
  },
  {
    name: '[/握手]',
    index: 112,
    path: 'woshou.png',
    asset: require('./woshou.png'),
  },
  {
    name: '[/抱拳]',
    index: 113,
    path: 'baoquan.png',
    asset: require('./baoquan.png'),
  },
  {
    name: '[/勾引]',
    index: 114,
    path: 'gouyin.png',
    asset: require('./gouyin.png'),
  },
  {
    name: '[/拳头]',
    index: 115,
    path: 'quantou.png',
    asset: require('./quantou.png'),
  },
  { name: '[/弱]', index: 116, path: 'ruo.png', asset: require('./ruo.png') },
  {
    name: '[/胜利]',
    index: 117,
    path: 'shengli.png',
    asset: require('./shengli.png'),
  },
  {
    name: '[/右边]',
    index: 118,
    path: 'youbian.png',
    asset: require('./youbian.png'),
  },
  {
    name: '[/左边]',
    index: 119,
    path: 'zuobian.png',
    asset: require('./zuobian.png'),
  },
  {
    name: '[/嘴唇]',
    index: 120,
    path: 'kiss.png',
    asset: require('./kiss.png'),
  },
  {
    name: '[/爱心]',
    index: 121,
    path: 'xin.png',
    asset: require('./xin.png'),
  },
  {
    name: '[/心碎]',
    index: 122,
    path: 'shangxin.png',
    asset: require('./shangxin.png'),
  },
  {
    name: '[/玫瑰]',
    index: 123,
    path: 'meigui.png',
    asset: require('./meigui.png'),
  },
  {
    name: '[/凋谢]',
    index: 124,
    path: 'diaoxie.png',
    asset: require('./diaoxie.png'),
  },
  {
    name: '[/啤酒]',
    index: 125,
    path: 'pijiu.png',
    asset: require('./pijiu.png'),
  },
  {
    name: '[/咖啡]',
    index: 126,
    path: 'kafei.png',
    asset: require('./kafei.png'),
  },
  {
    name: '[/蛋糕]',
    index: 127,
    path: 'dangao.png',
    asset: require('./dangao.png'),
  },
  {
    name: '[/礼物]',
    index: 128,
    path: 'liwu.png',
    asset: require('./liwu.png'),
  },
  {
    name: '[/撒花]',
    index: 129,
    path: 'sahua.png',
    asset: require('./sahua.png'),
  },
  { name: '[/V5]', index: 130, path: 'V5.png', asset: require('./V5.png') },
  { name: '[/绝]', index: 131, path: 'jue.png', asset: require('./jue.png') },
  { name: '[/666]', index: 132, path: '666.png', asset: require('./666.png') },
  {
    name: '[/给力]',
    index: 133,
    path: 'geili.png',
    asset: require('./geili.png'),
  },
  {
    name: '[/红包]',
    index: 134,
    path: 'hongbao.png',
    asset: require('./hongbao.png'),
  },
  { name: '[/屎]', index: 135, path: 'shi.png', asset: require('./shi.png') },
  { name: '[/发]', index: 136, path: 'fa.png', asset: require('./fa.png') },
  {
    name: '[/我太难了]',
    index: 137,
    path: 'wotainanle.png',
    asset: require('./wotainanle.png'),
  },
  {
    name: '[/18禁]',
    index: 138,
    path: '18jin.png',
    asset: require('./18jin.png'),
  },
  {
    name: '[/炸弹]',
    index: 139,
    path: 'zhadan.png',
    asset: require('./zhadan.png'),
  },
  {
    name: '[/去污粉]',
    index: 140,
    path: 'quwufen.png',
    asset: require('./quwufen.png'),
  },
  {
    name: '[/西瓜]',
    index: 141,
    path: 'xigua.png',
    asset: require('./xigua.png'),
  },
  {
    name: '[/加鸡腿]',
    index: 142,
    path: 'jiajitui.png',
    asset: require('./jiajitui.png'),
  },
  {
    name: '[/我酸了]',
    index: 143,
    path: 'wosuanle.png',
    asset: require('./wosuanle.png'),
  },
  {
    name: '[/握爪]',
    index: 144,
    path: 'wozhua.png',
    asset: require('./wozhua.png'),
  },
  {
    name: '[/太阳]',
    index: 145,
    path: 'taiyang.png',
    asset: require('./taiyang.png'),
  },
  {
    name: '[/月亮]',
    index: 146,
    path: 'yueliang.png',
    asset: require('./yueliang.png'),
  },
  {
    name: '[/给跪了]',
    index: 147,
    path: 'geiguile.png',
    asset: require('./geiguile.png'),
  },
  {
    name: '[/蕉绿]',
    index: 148,
    path: 'jiaolv.png',
    asset: require('./jiaolv.png'),
  },
  {
    name: '[/扎心]',
    index: 149,
    path: 'zhaxin.png',
    asset: require('./zhaxin.png'),
  },
  {
    name: '[/胡瓜]',
    index: 150,
    path: 'hugua.png',
    asset: require('./hugua.png'),
  },
  {
    name: '[/yyds]',
    index: 151,
    path: 'yyds.png',
    asset: require('./yyds.png'),
  },
  { name: '[/emo]', index: 152, path: 'emo.png', asset: require('./emo.png') },
  {
    name: '[/开心兔]',
    index: 153,
    path: 'kaixintu.png',
    asset: require('./kaixintu.png'),
  },
  {
    name: '[/招财兔]',
    index: 154,
    path: 'zhaocaitu.png',
    asset: require('./zhaocaitu.png'),
  },
  {
    name: '[/年兽兔]',
    index: 155,
    path: 'nianshoutu.png',
    asset: require('./nianshoutu.png'),
  },
  {
    name: '[/打call]',
    index: 156,
    path: 'dacall.png',
    asset: require('./dacall.png'),
  },
  {
    name: '[/栓Q]',
    index: 157,
    path: 'shuanq.png',
    asset: require('./shuanq.png'),
  },
  {
    name: '[/无语]',
    index: 158,
    path: 'wuyu.png',
    asset: require('./wuyu.png'),
  },
  {
    name: '[/雪人]',
    index: 159,
    path: 'xueren.png',
    asset: require('./xueren.png'),
  },
  {
    name: '[/雪花]',
    index: 160,
    path: 'xuehua.png',
    asset: require('./xuehua.png'),
  },
  {
    name: '[/圣诞树]',
    index: 161,
    path: 'shengdanshu.png',
    asset: require('./shengdanshu.png'),
  },
  {
    name: '[/平安果]',
    index: 162,
    path: 'pinganguo.png',
    asset: require('./pinganguo.png'),
  },
  {
    name: '[/圣诞帽]',
    index: 163,
    path: 'shengdanmao.png',
    asset: require('./shengdanmao.png'),
  },
  {
    name: '[/气球]',
    index: 164,
    path: 'qiqiu.png',
    asset: require('./qiqiu.png'),
  },
  {
    name: '[/干杯]',
    index: 165,
    path: 'ganbei.png',
    asset: require('./ganbei.png'),
  },
  {
    name: '[/烟花]',
    index: 166,
    path: 'yanhua.png',
    asset: require('./yanhua.png'),
  },
  { name: '[/福]', index: 167, path: 'fu.png', asset: require('./fu.png') },
  {
    name: '[/candy]',
    index: 168,
    path: 'candy.png',
    asset: require('./candy.png'),
  },
  {
    name: '[/糖葫芦]',
    index: 169,
    path: 'tanghulu.png',
    asset: require('./tanghulu.png'),
  },
  {
    name: '[/虎头]',
    index: 170,
    path: 'hutou.png',
    asset: require('./hutou.png'),
  },
  {
    name: '[/饺子]',
    index: 171,
    path: 'jiaozi.png',
    asset: require('./jiaozi.png'),
  },
  {
    name: '[/鞭炮]',
    index: 172,
    path: 'bianpao.png',
    asset: require('./bianpao.png'),
  },
  {
    name: '[/元宝]',
    index: 173,
    path: 'yuanbao.png',
    asset: require('./yuanbao.png'),
  },
  {
    name: '[/灯笼]',
    index: 174,
    path: 'denglong.png',
    asset: require('./denglong.png'),
  },
  {
    name: '[/锦鲤]',
    index: 175,
    path: 'jinli.png',
    asset: require('./jinli.png'),
  },
  {
    name: '[/巧克力]',
    index: 176,
    path: 'qiaokeli.png',
    asset: require('./qiaokeli.png'),
  },
  {
    name: '[/汤圆]',
    index: 177,
    path: 'tangyuan.png',
    asset: require('./tangyuan.png'),
  },
  {
    name: '[/情书]',
    index: 178,
    path: 'qingshu.png',
    asset: require('./qingshu.png'),
  },
  {
    name: '[/iloveyou]',
    index: 179,
    path: 'iloveyou.png',
    asset: require('./iloveyou.png'),
  },
  {
    name: '[/戒指]',
    index: 180,
    path: 'jiezhi.png',
    asset: require('./jiezhi.png'),
  },
  {
    name: '[/派对]',
    index: 181,
    path: 'sahua.png',
    asset: require('./sahua.png'),
  },
  {
    name: '[/象]',
    index: 182,
    path: 'xiang.png',
    asset: require('./xiang.png'),
  },
]
